// Generated by CoffeeScript 1.6.1
(function() {
  var Frame;

  Frame = (function() {
    var applyXYZ, calcAccel, calcEndVelocity, calcPosition, calcPositionDelta, calcTimeDelta;

    function Frame(lastFrame, accelValues) {
      this.lastFrame = lastFrame;
      this.gAccel = accelValues.slice(0, 3);
      this.accel = calcAccel.call(this);
      this.timestamp = accelValues.slice(3, 4);
      this.timeDelta = calcTimeDelta.call(this);
      this.endVelocity = calcEndVelocity.call(this);
      this.positionDelta = calcPositionDelta.call(this);
      this.position = calcPosition.call(this);
    }

    Frame.prototype.toTableRow = function() {
      var in_mm, to_mm;
      to_mm = function(coord) {
        return this.position[coord] * 1000;
      };
      in_mm = applyXYZ.call(this, to_mm);
      return "" + in_mm[0] + ", " + in_mm[1] + ", " + in_mm[2];
    };

    calcAccel = function() {
      var times9_8;
      times9_8 = function(val) {
        return val * 9.801;
      };
      return this.gAccel.map(times9_8, this);
    };

    calcTimeDelta = function() {
      return (this.timestamp - this.lastFrame.timestamp) / 1000;
    };

    calcEndVelocity = function() {
      var velocity;
      velocity = function(coord) {
        return this.accel[coord] * this.timeDelta;
      };
      return applyXYZ.call(this, velocity);
    };

    calcPositionDelta = function() {
      var posDelta;
      posDelta = function(coord) {
        var v0_t;
        v0_t = this.lastFrame.endVelocity[coord] * this.timeDelta;
        return v0_t + 1 / 2 * this.accel[coord] * Math.pow(this.timeDelta, 2);
      };
      return applyXYZ.call(this, posDelta);
    };

    calcPosition = function() {
      var newPosition;
      newPosition = function(coord) {
        return this.lastFrame.position[coord] + this.positionDelta[coord];
      };
      return applyXYZ.call(this, newPosition);
    };

    applyXYZ = function(fcn) {
      return [0, 1, 2].map(fcn, this);
    };

    return Frame;

  })();

  module.exports = Frame;

}).call(this);
