// Generated by CoffeeScript 1.6.1
(function() {
  var InitialFrame;

  InitialFrame = (function() {
    var applyXYZ, calcAccel;

    function InitialFrame(accelValues) {
      this.gAccel = accelValues.slice(0, 3);
      this.accel = calcAccel.call(this);
      this.timestamp = accelValues.slice(3, 4);
      this.timeDelta = [0, 0, 0];
      this.endVelocity = [0, 0, 0];
      this.positionDelta = [0, 0, 0];
      this.position = [0, 0, 0];
    }

    InitialFrame.prototype.tare = function(accelValues) {
      var tare;
      tare = function(coord) {
        return accelValues[coord] - this.gAccel[coord];
      };
      return applyXYZ.call(this, tare).concat(accelValues[3]);
    };

    calcAccel = function() {
      var times9_8;
      times9_8 = function(val) {
        return val * 9.801;
      };
      return this.gAccel.map(times9_8, this);
    };

    applyXYZ = function(fcn) {
      return [0, 1, 2].map(fcn, this);
    };

    return InitialFrame;

  })();

  module.exports = InitialFrame;

}).call(this);
