// Generated by CoffeeScript 1.6.1
(function() {
  var Frame, InitialFrame, MMA8452Q, accelerometer, afterInit, initPrevious, nTimes, previousValue;

  Frame = require("./Frame");

  InitialFrame = require("./InitialFrame");

  MMA8452Q = require("./MMA8452Q");

  accelerometer = new MMA8452Q;

  previousValue = [0, 0, 0, 0];

  nTimes = 30;

  initPrevious = function(times, afterInit) {
    var computeNext;
    if (!times) {
      return afterInit();
    }
    computeNext = function(values) {
      var pX, pY, pZ, stamp, x, y, z;
      x = values[0], y = values[1], z = values[2], stamp = values[3];
      pX = previousValue[0], pY = previousValue[1], pZ = previousValue[2];
      return previousValue = [pX + x / nTimes, pY + y / nTimes, pZ + z / nTimes, stamp];
    };
    return accelerometer.read(function(err, values) {
      computeNext(values);
      return initPrevious(times - 1, afterInit);
    });
  };

  afterInit = function() {
    var initFrame, step;
    console.log("Starting With: ", previousValue);
    initFrame = new InitialFrame(previousValue);
    step = function(lastFrame) {
      return function() {
        return accelerometer.read(function(err, values) {
          var newFrame;
          if (err) {
            return console.log(err);
          }
          newFrame = new Frame(lastFrame, initFrame.tare(values));
          console.log(newFrame.toTableRow());
          return setTimeout(step(newFrame), 50);
        });
      };
    };
    return step(initFrame)();
  };

  initPrevious(nTimes, afterInit);

}).call(this);
