// Generated by CoffeeScript 1.6.1
(function() {
  var MMA8452Q, accelerometer, afterInit, initPrevious, nTimes, previousValue;

  MMA8452Q = require("./MMA8452Q");

  accelerometer = new MMA8452Q;

  previousValue = [0, 0, 0, 0];

  afterInit = function() {
    return console.log(previousValue);
  };

  nTimes = 20;

  initPrevious = function(times, afterInit) {
    var computeNext;
    if (!times) {
      return afterInit();
    }
    computeNext = function(values) {
      var pX, pY, pZ, stamp, x, y, z;
      x = values[0], y = values[1], z = values[2], stamp = values[3];
      pX = previousValue[0], pY = previousValue[1], pZ = previousValue[2];
      return previousValue = [pX + x / nTimes, pY + y / nTimes, pZ + z / nTimes, stamp];
    };
    return accelerometer.read(function(err, values) {
      computeNext(values);
      return initPrevious(times - 1, afterInit);
    });
  };

  initPrevious(nTimes, afterInit);

}).call(this);
