// Generated by CoffeeScript 1.6.1
(function() {
  var MMA8452Q, accelerometer, read;

  MMA8452Q = require("./MMA8452Q");

  accelerometer = new MMA8452Q;

  read = function() {
    return accelerometer.read(function(err, values) {
      var realX, realY, realZ;
      realX = values[0], realY = values[1], realZ = values[2];
      return console.log("[ ", realX, ", ", realY, ", ", realZ, " ] - ", Math.sqrt(Math.pow(realX, 2) + Math.pow(realY, 2) + Math.pow(realZ, 2)));
    });
  };

  setInterval(read, 100);

}).call(this);
