// Generated by CoffeeScript 1.6.1
(function() {
  var PositionTracker, app, connect, fs, io, positionTracker, server;

  connect = require("connect");

  app = connect().use(connect["static"]("vendor")).use(connect["static"]("public"));

  server = app.listen(process.env.port || 3000);

  io = require("socket.io").listen(server);

  fs = require("fs");

  PositionTracker = require("../reader-js/PositionTracker");

  positionTracker = new PositionTracker(5);

  positionTracker.start();

  io.set("log level", 1);

  io.sockets.on("connection", function(socket) {
    return positionTracker.on("data", function(frame) {
      return socket.emit("update", frame.position);
    });
  });

}).call(this);
